apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: akpfs
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
  - name: deploy-trigger-for-front
    interceptors:
    - github:
        eventTypes: ["push"]
    - cel:
        filter: "body.repository.name == 'team-taurus-frontend' && body.ref.split('/')[2] == 'main'"
    bindings:
      - ref: taurus-frontend-pipeline-from-scratch-pipeline-triggerbinding
    template:
      ref: team-taurus-frontend-pipeline-from-scratch-triggertemplate
