apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: team-taurus-frontend-pipeline-from-scratch-triggertemplate
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: team-taurus-frontend-pipeline-from-scratch-pipeline-run-
      spec:
        serviceAccountName: build-bot
        pipelineRef:
          name: team-taurus-frontend-pipeline-from-scratch-pipeline
        workspaces:
          - name: pipeline-shared-data
            persistentVolumeClaim:
              claimName: team-taurus-frontend-pvc
