apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    app.openshift.io/runtime: nodejs
  name: taurus-frontend-pipeline-from-scratch-pipeline
spec:
  workspaces:
    - name: pipeline-shared-data
      description: |
        This workspace stores the cloned repository and is available to all steps
  params:
    - name: image-repo
      type: string
      description: Docker image name
      default: quay.io/shinnosuke_yoshizawa_ibm/team-taurus-frontend
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: https://github.com/cloud-native-garage-method-japan-cohort/team-taurus-frontend.git
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-shared-data
    - name: install-dependencies
      runAfter:
        - clone-repository
      taskRef:
        kind: Task
        name: npm
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      params:
        - name: ARGS
          value: 
            - clean-install
    - name: run-tests
      runAfter:
        - install-dependencies
      taskRef:
        kind: Task
        name: npm
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      params:
        - name: ARGS
          value: 
            - test
    - name: build-image
      runAfter:
        - run-tests
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      params:
        - name: IMAGE
          value: "$(params.image-repo):$(tasks.clone-repository.results.commit)"
    - name: kustomize-build
      runAfter:
        - build-image
      taskRef:
        kind: Task
        name: kustomize-build
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      params:
        - name: image-with-tag
          value: "quay.io/shinnosuke_yoshizawa_ibm/team-taurus-frontend=$(params.image-repo):$(tasks.clone-repository.results.commit)"
    - name: test-deploy
      runAfter:
        - kustomize-build
      taskRef:
        kind: Task
        name: test-deploy
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      params:
        - name: app-namespace
          value: team-taurus-frontend
        - name: app-name
          value: team-taurus-frontend
