apiVersion: v1
kind: Service
metadata:
  labels:
    app: team-taurus-frontend
    app.kubernetes.io/instance: team-taurus-frontend
    app.kubernetes.io/name: team-taurus-frontend
  name: team-taurus-frontend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/instance: team-taurus-frontend
    app.kubernetes.io/name: team-taurus-frontend
  sessionAffinity: None
  type: ClusterIP
